production:
  solr:
    hostname: <%= ENV["SOLR_HOST"] %>
    port: 8983
    log_level: WARNING
    path: /solr/<%= ENV["SOLR_CORE"] %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/mapseries

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    